project:
  name: record
spring:
  kafka:
    consumer:
      bootstrap-servers: kafka1.skye.dafy.com:9092,kafka2.skye.dafy.com:9092,kafka3.skye.dafy.com:9092
      auto-offset-reset: latest
      group-id: gw-record
    listener:
      poll-timeout: 300
      concurrency: 8
  data:
    mongodb:
      host: mongodb.dafy.com
      port: 27017
      # username: dafyadmin
      # password: dafyadmin
      database: gateway
dubbo:
  application:
    name: gateway-record-consumer
  registry:
    address: zookeeper://zookeeper1.dafy.com:2181?backup=zookeeper2.dafy.com:2181,zookeeper3.dafy.com:2181
  annotation:
    package: com.dafy.base.gateway.record.service